ALTER TABLE "User" ADD COLUMN "allowMessageRequests" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "allowGroupInvites" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "allowStoryReplies" BOOLEAN NOT NULL DEFAULT true;
